### ISSUE TITLE
动画细节封装

### ISSUE THREAD

**Issue by 011011100** [elonehoo/ui#2]
身为一个喜欢挑刺的人我很抱歉🤗
但是我不得不提出这个问题❓
一个下落回弹的动画我居然只能控制整体的动画时间⏱️
这可真是太遗憾了😿
我觉得可以对动画的细节部分也进行封装👍🏻
大的要，小的也要，这样才称得上是健全💪🏻

**Comment by elonehoo** [comment]
那是由 [unocss](https://github.com/unocss/unocss) 支持的，如果你想要控制更多的动画可以区单独的控制每一个动画的参数，可以去了解一下，或者可以使用 [animated-unocss](https://github.com/conver-unocss/animated-unocss)
